name: Docker Image CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the JRG Docker image
      run: docker build ./ --file docker/Dockerfile --tag jrg:$(date +%s)

